# Motor Control Settings
DEADZONE = 10
THROTTLE_AXIS = 3
STEERING_AXIS = 2
ESP_IP = None # FILL IN IP
ESP_PORT = 4210

# Video Capture Settings
JOSHPI_DISPLAY_SIZE = (640, 480)
JOSHPI_IP = None # FILL IN IP
JOSHPI_PORT = "8554"

# Autonomous Control settings
YOLO_INPUT_SIZE = 640 #expects multiple of 32
MODEL = "yolov8m.pt"
DEVICE = "cuda"
AUTONOMOUS_THROTTLE_SPEED = 160 # 0-255
AUTONOMOUS_STEERING_SPEED = 60 # 0-255
CLASS_IDS = [0] # YOLO classes: person
TIMEOUT = 0.1
CONFIDENCE = 0.5
SLEEP_TIME = 0.05
DECAY = 0.95
